export const PREV_IMG = 'PREV_IMG'
export const NEXT_IMG = 'NEXT_IMG'
export const TAKEIMG_SUCCESS = 'TAKEIMG_SUCCESS'
export const CHANGE_SLIDER = 'CHANGE_SLIDER'
export const SET_LENGTH = 'SET_LENGTH'
